// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvdhqusjujqrwerwtyhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2ZGhxdXNqdWpxcndlcnd0eWhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MDMwMzQsImV4cCI6MjA2NDI3OTAzNH0.y1ueQtOZYg2pRHjGIW5PVt2q8OT5QnbYFby55_6Irpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    // Keep sessions active indefinitely until explicit logout
    flowType: 'pkce'
  },
  // Add retry configuration for better mobile stability
  db: {
    schema: 'public',
  },
  global: {
    headers: {
      'X-Client-Info': 'nutriwealth-app'
    }
  }
});
